### ISSUE TITLE
torch.speical.i1 typo

### ISSUE THREAD

**Issue by torridgristle** [junjun3518/alias-free-torch#1]
https://github.com/junjun3518/alias-free-torch/blob/f1fddd52fdd068ee475e82ae60c92e1bc24ffe02/src/alias_free_torch/filter.py#L22

At this line I believe you wanted torch.special.i1.

**Comment by junjun3518** [comment]
Oh so many typos... 
Thank you for pointing out my mistakes!

**Comment by junjun3518** [comment]
fixed at commit https://github.com/junjun3518/alias-free-torch/commit/eb1973e7d7f2054536194d89f40f8121e51f702f

Thank you for finding typos again
