### ISSUE TITLE
Padding Bool typo

### ISSUE THREAD

**Issue by torridgristle** [junjun3518/alias-free-torch#3]
https://github.com/junjun3518/alias-free-torch/blob/258551410ff7bf02e06ece7c597466dc970fe5c7/src/alias_free_torch/filter.py#L73

`padding: bool: True,` should be `padding: bool = True,`

I'm not sure if this causes an error with every version of PyTorch, but it does with PyTorch 1.12.0+cu113 on Python 3.7.13

**Comment by junjun3518** [comment]
`padding: bool: True`is replaced as `padding: bool = True`
Thank you for your great interest! 
Since it is my side work, there are too many mistakes...
