### ISSUE TITLE
"if self.pad / self.padding" in LowPassFilter2d

### ISSUE THREAD

**Issue by torridgristle** [junjun3518/alias-free-torch#4]
https://github.com/junjun3518/alias-free-torch/blob/258551410ff7bf02e06ece7c597466dc970fe5c7/src/alias_free_torch/filter.py#L165
https://github.com/junjun3518/alias-free-torch/blob/258551410ff7bf02e06ece7c597466dc970fe5c7/src/alias_free_torch/filter.py#L173

In LowPassFilter2d it looks like `if self.pad:` should change to `if self.padding:`, or `self.padding = padding` should change to `self.pad = padding` to match LowPassFilter1d.

**Comment by junjun3518** [comment]
Replace `if self.pad:` to `if self.padding:`

Thank you for find my mistake
